WaterProject/Components/TypesViewComponent.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WaterProject.Models;

namespace WaterProject.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IWaterProjectRepository Repo { get; set; }

        public TypesViewComponent (IWaterProjectRepository repo)
        {
            Repo = repo;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["projectType"];

            var types = Repo.Projects
                .Select(x => x.ProjectType)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

WaterProject/Views/Shared/ProjectSummary.cshtml
@{
}

@model ProjectModel;

<div class="card outline-primary m-1 p-1">
    <div class="bg-light p-1">
        <h4>@Model.ProjectName</h4>

        <span class="badge bg-primary" style="float:right">
            Impact: @Model.ProjectImpact Served
        </span>
    </div>

    <ul>
        <li>Project Type: @Model.ProjectType</li>
        <li>Regional Program: @Model.ProjectRegionalProgram</li>
        <li>Project Phase: @Model.ProjectPhase</li>
        <li>Project Status: @Model.ProjectFunctionalityStatus</li>
    </ul>

    <form method="post" asp-page="/Donate">
        <input type="hidden" asp-for="@Model.ProjectID" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm">Donate</button>
        </span>
    </form>
</div>

WaterProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-4">
        <span class="navbar-brand">Water Project</span>
    </div>

    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>

        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>

    </div>

</body>
</html>