WaterProject/Controllers/DonationController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WaterProject.Models;

namespace WaterProject.Controllers
{
    public class DonationController : Controller
    {
        private IDonationRepository Repo { get; set; }
        private Basket Basket { get; set; }

        public DonationController(IDonationRepository repository, Basket b)
        {
            Repo = repository;
            Basket = b;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Donation());
        }

        [HttpPost]
        public IActionResult Checkout(Donation donation)
        {
            if (Basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry your basket is empty");
            }

            if (ModelState.IsValid)
            {
                donation.Lines = Basket.Items.ToArray();
                Repo.SaveDonation(donation);
                Basket.ClearBasket();

                return RedirectToPage("/DonationComplete");
            } else
            {
                return View();
            }
        }
    }
}

WaterProject/Pages/Donate.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WaterProject.Infrastructure;
using WaterProject.Models;

namespace WaterProject.Pages
{
    public class DonateModel : PageModel
    {
        private IWaterProjectRepository Repository { get; set; }

        public DonateModel(IWaterProjectRepository repository, Basket b)
        {
            Repository = repository;
            Basket = b;
        }

        public Basket Basket { get; set; }
        public string ReturnUrl { get; set; }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int projectId, string returnUrl)
        {
            ProjectModel project = Repository.Projects
                .FirstOrDefault(project => project.ProjectID == projectId);

            Basket.AddItem(project, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(int projectId, string returnUrl)
        {
            Basket.RemoveItem(Basket.Items.First(x => x.Project.ProjectID == projectId).Project);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

WaterProject/Pages/DonationComplete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WaterProject.Pages
{
    public class DonationCompleteModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WaterProject/Pages/Donate.cshtml
@page
@model WaterProject.Pages.DonateModel
@{
}

<h2>Your Basket</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var i in Model.Basket.Items)
        {
            <tr>
                <td>@i.Project.ProjectName</td>
                <td>@i.Quantity</td>
                <td>$25.00</td>
                <td>@((i.Quantity * 12).ToString("c"))</td>
                <td class="text-center">
                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="projectId" value="@i.Project.ProjectID" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.Basket.CalculateTotal().ToString("C")</td>
        </tr>
    </tfoot>
</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Donating</a>
    <a class="btn btn-primary" asp-controller="Donation" asp-action="Checkout">Checkout</a>
</div>

WaterProject/Pages/DonationComplete.cshtml
@page
@model WaterProject.Pages.DonationCompleteModel
@{
}

<div class="text-center">
    <h2>Thanks! Your order will make a difference!</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

WaterProject/Pages/_DonateLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-4">
        <span class="navbar-brand">Water Project</span>
    </div>

    <div class="row m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>